# Generated by Django 4.2.1 on 2023-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_cart_total_alter_cart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
