# Generated by Django 4.2.1 on 2023-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_cart_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('pinCode', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('HouseName', models.CharField(max_length=150)),
                ('landMark', models.CharField(max_length=150)),
            ],
        ),
    ]
