# Generated by Django 4.2.1 on 2023-06-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
