# Generated by Django 4.2.1 on 2023-09-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
