# Generated by Django 4.2.1 on 2023-06-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='mainimage/')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
