# Generated by Django 4.2.1 on 2023-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ImageField(upload_to='mainimage'),
        ),
    ]
